# Версия API
apiVersion: apps/v1
# Тип объекта - развертывание
kind: Deployment
metadata:
  # Имя развертывания
  name: mifiib-deployment
  labels:
    # Метка приложения
    app: mifiib
spec:
  # Количество реплик
  replicas: 1
  selector:
    matchLabels:
      # Селектор для соответствия меткам приложения
      app: mifiib
  template:
    metadata:
      labels:
        # Метка для шаблона
        app: mifiib
    spec:
      containers:
      # Имя контейнера
      - name: mifiibdb
        # Образ контейнера
        image: yana-db
        imagePullPolicy: Never
        ports:
        # Порт контейнера
        - containerPort: 3306
        resources:
          limits:
            # Лимит ресурсов CPU
            cpu: "0.5"
            # Лимит ресурсов памяти
            memory: "512Mi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              # Имя секрета
              name: mifiib-secret
              # Ключ секрета для значения переменной среды
              key: root_password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              # Имя секрета
              name: mifiib-secret
              # Ключ секрета для значения переменной среды
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              # Имя секрета
              name: mifiib-secret
              # Ключ секрета для значения переменной среды
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              # Имя секрета
              name: mifiib-secret
              # Ключ секрета для значения переменной среды
              key: password
---

# Версия API для сервиса
apiVersion: v1
# Тип объекта - сервис
kind: Service
metadata:
  # Имя сервиса
  name: mifiib-service
spec:
  selector:
    # Селектор для соответствия меткам приложения
    app: mifiib
  ports:
    - protocol: TCP
      # Порт сервиса
      port: 3306
      # Целевой порт
      targetPort: 3306
